# Generated by Django 4.2.4 on 2023-11-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
