# Generated by Django 4.2.4 on 2023-11-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_alter_uom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uom',
            name='unit',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uom',
            name='weightage',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
