# Generated by Django 4.2.4 on 2023-11-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_uom_unit_uom_weightage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='weightage',
            field=models.FloatField(),
        ),
    ]
