# Generated by Django 4.2.4 on 2023-11-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectronicInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_purchase', models.DateField()),
                ('status', models.CharField(choices=[('1', 'Idle'), ('2', 'In-use')], default=1, max_length=2)),
                ('remark', models.CharField(max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectronicUserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('careholder_name', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectronicUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('position', models.CharField(max_length=100, unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.electronicuserlocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectronicTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('1', 'Log-Out'), ('2', 'Log-In')], default=1, max_length=2)),
                ('initial_agreement_doc', models.FileField(upload_to='office/agreement/initial')),
                ('return_agreement_doc', models.FileField(blank=True, upload_to='office/agreement/return')),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.electronicuser')),
                ('electronic_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.electronicinventory')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicPurchasingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=200, null=True)),
                ('po_doc', models.FileField(upload_to='office/purchasing_documents/PO')),
                ('invoice_number', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice_doc', models.FileField(upload_to='office/purchasing_documents/invoice')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchasing.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectronicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.electronicbrand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='electronicinventory',
            name='electronic_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.electronicmodel'),
        ),
        migrations.AddField(
            model_name='electronicinventory',
            name='previous_users',
            field=models.ManyToManyField(related_name='previous_users', to='office.electronicuser'),
        ),
        migrations.AddField(
            model_name='electronicinventory',
            name='purchasing_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.electronicpurchasingdocument'),
        ),
    ]
