# Generated by Django 4.2.4 on 2023-11-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_electronicbrand_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicinventory',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='electronicinventory',
            name='status',
            field=models.CharField(choices=[('Idle', 'Idle'), ('In-use', 'In-use')], default=1, max_length=10),
        ),
    ]
