# Generated by Django 4.2.4 on 2023-11-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_alter_electronicinventory_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronictransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Log-Out', 'Log-Out'), ('Log-In', 'Log-In')], default=1, max_length=10),
        ),
    ]
