# Generated by Django 4.2.4 on 2023-11-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_alter_electronictransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicinventory',
            name='status',
            field=models.CharField(choices=[('Idle', 'Idle'), ('In-Use', 'In-Use')], default='Idle', max_length=10),
        ),
        migrations.AlterField(
            model_name='electronictransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Log-Out', 'Log-Out'), ('Log-In', 'Log-In')], default='Log-Out', max_length=10),
        ),
    ]
