# Generated by Django 4.2.4 on 2023-11-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_alter_electronicinventory_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronictransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Checked-Out', 'Checked-Out'), ('Checked-In', 'Checked-In')], default='Checked-Out', max_length=20),
        ),
    ]
