# Generated by Django 4.2.4 on 2023-11-26 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_alter_electronictransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicpurchasingdocument',
            name='invoice_doc',
            field=models.FileField(help_text='Maximum file size: 5 MB. Allowed extensions: .pdf', upload_to='office/purchasing_documents/invoice', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='electronicpurchasingdocument',
            name='po_doc',
            field=models.FileField(help_text='Maximum file size: 5 MB. Allowed extensions: .pdf', upload_to='office/purchasing_documents/PO', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='electronictransaction',
            name='initial_agreement_doc',
            field=models.FileField(help_text='Maximum file size: 5 MB. Allowed extensions: .pdf', upload_to='office/agreement/initial', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='electronictransaction',
            name='return_agreement_doc',
            field=models.FileField(blank=True, help_text='Maximum file size: 5 MB. Allowed extensions: .pdf', upload_to='office/agreement/return', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
