# Generated by Django 4.2.4 on 2023-11-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_alter_electronicpurchasingdocument_invoice_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicpurchasingdocument',
            name='invoice_doc',
            field=models.FileField(help_text='Maximum file size: 5 MB. Allowed extensions: .pdf', upload_to='office/purchasing_documents/invoice'),
        ),
        migrations.AlterField(
            model_name='electronicpurchasingdocument',
            name='po_doc',
            field=models.FileField(help_text='Maximum file size: 5 MB. Allowed extensions: .pdf', upload_to='office/purchasing_documents/PO'),
        ),
        migrations.AlterField(
            model_name='electronictransaction',
            name='initial_agreement_doc',
            field=models.FileField(help_text='Maximum file size: 5 MB. Allowed extensions: .pdf', upload_to='office/agreement/initial'),
        ),
        migrations.AlterField(
            model_name='electronictransaction',
            name='return_agreement_doc',
            field=models.FileField(blank=True, help_text='Maximum file size: 5 MB. Allowed extensions: .pdf', upload_to='office/agreement/return'),
        ),
    ]
