# Generated by Django 4.2.4 on 2023-12-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_alter_electronicuserlocation_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicuser',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
