# Generated by Django 4.2.4 on 2023-09-30 14:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0020_alter_quotationitem_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitiy_used', models.FloatField(default=0)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('spec', models.CharField(blank=True, max_length=200, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_item_code', models.CharField(max_length=20, unique=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('representative_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.PositiveIntegerField(null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator()])),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(blank=True, max_length=200, null=True)),
                ('exp_date', models.DateTimeField()),
                ('price_unit', models.CharField(blank=True, max_length=200, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.rawmaterialcomponent')),
            ],
        ),
        migrations.AddField(
            model_name='rawmaterialcomponent',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.rawmaterialidentifier'),
        ),
        migrations.CreateModel(
            name='PurchasingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=200, null=True)),
                ('po_doc', models.FileField(upload_to='purchase_documents/PO')),
                ('invoice_number', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice_doc', models.FileField(upload_to='purchase_documents/invoice')),
                ('packing_list', models.CharField(blank=True, max_length=200, null=True)),
                ('pl_doc', models.FileField(upload_to='purchase_documents/PL')),
                ('k1_form', models.CharField(blank=True, max_length=200, null=True)),
                ('k1_doc', models.FileField(upload_to='purchase_documents/K1')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rH', models.PositiveIntegerField()),
                ('temperature', models.PositiveIntegerField()),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('BOMComponents', models.ManyToManyField(to='purchasing.bomcomponent')),
            ],
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='raw_material_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.rawmaterialcomponent'),
        ),
    ]
