# Generated by Django 4.2.4 on 2023-11-18 09:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('representative_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.PositiveIntegerField(null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator()])),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('currency_trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='misc.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchasingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=200, null=True)),
                ('po_doc', models.FileField(upload_to='purchasing_documents/PO')),
                ('invoice_number', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice_doc', models.FileField(upload_to='purchasing_documents/invoice')),
                ('packing_list', models.CharField(blank=True, max_length=200, null=True)),
                ('pl_doc', models.FileField(upload_to='purchasing_documents/PL')),
                ('k1_form', models.CharField(blank=True, max_length=200, null=True)),
                ('k1_doc', models.FileField(upload_to='purchasing_documents/K1')),
                ('k1_form_rate', models.FloatField()),
                ('AWB_number', models.CharField(blank=True, max_length=200, null=True)),
                ('AWB_doc', models.FileField(upload_to='purchasing_documents/AWB')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchasing.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
