# Generated by Django 4.2.4 on 2023-10-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bomcomponent',
            old_name='quantitiy_used',
            new_name='quantity_used',
        ),
        migrations.AddField(
            model_name='productionlog',
            name='exp_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productionlog',
            name='lot_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
