# Generated by Django 4.2.4 on 2023-11-26 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasingdocument',
            name='po_doc',
            field=models.FileField(help_text='Maximum file size: 5 MB. Allowed extensions: .pdf', upload_to='purchasing_documents/PO', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
