# Generated by Django 4.2.4 on 2023-10-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_rename_quantitiy_used_bomcomponent_quantity_used_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterialinventory',
            old_name='lot',
            new_name='lot_number',
        ),
        migrations.RenameField(
            model_name='rawmaterialinventory',
            old_name='price_unit',
            new_name='price_per_unit',
        ),
        migrations.AddField(
            model_name='rawmaterialinventory',
            name='stock_type',
            field=models.CharField(choices=[('1', 'Stock-in'), ('2', 'Stock-Out')], default=1, max_length=2),
        ),
    ]
