# Generated by Django 4.2.4 on 2023-11-26 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_alter_purchasingdocument_po_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasingdocument',
            name='AWB_doc',
            field=models.FileField(help_text='Maximum file size: 5 MB. Allowed extensions: .pdf', upload_to='purchasing_documents/AWB', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='purchasingdocument',
            name='invoice_doc',
            field=models.FileField(help_text='Maximum file size: 5 MB. Allowed extensions: .pdf', upload_to='purchasing_documents/invoice', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='purchasingdocument',
            name='k1_doc',
            field=models.FileField(help_text='Maximum file size: 5 MB. Allowed extensions: .pdf', upload_to='purchasing_documents/K1', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='purchasingdocument',
            name='pl_doc',
            field=models.FileField(help_text='Maximum file size: 5 MB. Allowed extensions: .pdf', upload_to='purchasing_documents/PL', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
