# Generated by Django 4.2.4 on 2023-10-12 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_rename_lot_rawmaterialinventory_lot_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialinventory',
            name='purchasing_doc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='purchasing.purchasingdocument'),
            preserve_default=False,
        ),
    ]
