# Generated by Django 4.2.4 on 2023-10-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_rawmaterialinventory_purchasing_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialinventory',
            name='exp_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
