# Generated by Django 4.2.4 on 2023-10-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0006_purchasingdocument_awb_doc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialinventory',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='rawmaterialinventory',
            name='update_date',
        ),
        migrations.AddField(
            model_name='rawmaterialinventory',
            name='stock_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialinventory',
            name='stock_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialinventory',
            name='validation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
