# Generated by Django 4.2.4 on 2023-10-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0008_rawmaterialinventory_stock_in_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialinventory',
            name='log_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
