# Generated by Django 4.2.4 on 2023-09-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('ProDetect', 'ProDetect'), ('GenoAmp', 'GenoAmp'), ('Wondfo', 'Wondfo'), ('Finecare', 'Finecare'), ('Sejoy', 'Sejoy')], max_length=20)),
                ('packing', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
