# Generated by Django 4.2.4 on 2023-09-06 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='type',
            field=models.CharField(choices=[('1', 'Stock-in'), ('2', 'Stock-Out')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default=1, max_length=2),
        ),
        migrations.RenameModel(
            old_name='Inquiry',
            new_name='Quotation',
        ),
        migrations.CreateModel(
            name='Quotation_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.quotation')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.inventory')),
            ],
        ),
    ]
