# Generated by Django 4.2.4 on 2023-09-06 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_inventory_type_product_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='stock_up_date',
            new_name='stock_in_date',
        ),
        migrations.AddField(
            model_name='inventory',
            name='expiry_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='lot_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
