# Generated by Django 4.2.4 on 2023-09-01 10:00

import django.core.validators
from django.db import migrations, models
import validator.posscode


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_product_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('posscode', models.PositiveIntegerField(validators=[validator.posscode.posscode_validator])),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator])),
                ('phone_number', models.CharField(max_length=100)),
                ('sales_person', models.CharField(max_length=100)),
            ],
        ),
    ]
