# Generated by Django 4.2.4 on 2023-09-06 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_stock_up_date_inventory_stock_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='currency_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=3, unique=True),
            preserve_default=False,
        ),
    ]
