# Generated by Django 4.2.4 on 2023-09-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_name_customer_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='product_id',
        ),
    ]
