# Generated by Django 4.2.4 on 2023-09-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_brandname_currency_deliverymethod_salesperson_uom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uom',
            options={'verbose_name_plural': 'UOM'},
        ),
    ]
