# Generated by Django 4.2.4 on 2023-09-12 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_customer_id_quotation_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.AddField(
            model_name='brandname',
            name='company_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='brandname',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='product_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesperson',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandname',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
