# Generated by Django 4.2.4 on 2023-09-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_currency_create_date_currency_update_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='name_acronym',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
