# Generated by Django 4.2.4 on 2023-09-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_salesperson_name_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name_acronym',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='doc_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
