# Generated by Django 4.2.4 on 2023-09-12 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_customer_name_acronym_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='sales_person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.salesperson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotation',
            name='doc_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
