# Generated by Django 4.2.4 on 2023-09-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_quotation_sales_person_alter_quotation_doc_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='product_id',
        ),
    ]
