# Generated by Django 4.2.4 on 2023-09-13 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_quotation_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Quotation_Item',
            new_name='QuotationItem',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='sales_person',
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.paymentterm'),
        ),
    ]
