# Generated by Django 4.2.4 on 2023-09-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_paymentterm_rename_quotation_item_quotationitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='payment_term',
        ),
        migrations.DeleteModel(
            name='PaymentTerm',
        ),
    ]
