# Generated by Django 4.2.4 on 2023-09-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_customer_payment_term_delete_paymentterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='doc_number',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
