# Generated by Django 4.2.4 on 2023-09-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_quotation_doc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='doc_number',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
