# Generated by Django 4.2.4 on 2023-09-17 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_quotation_doc_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('inv_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('tracking_number', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.deliverymethod')),
                ('quotation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.quotation')),
            ],
        ),
    ]
