# Generated by Django 4.2.4 on 2023-09-30 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_quotationitem_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotationitem_set', to='dashboard.quotation'),
        ),
    ]
