# Generated by Django 4.2.4 on 2023-11-18 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='identifier',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, to='production.rawmaterialidentifier'),
            preserve_default=False,
        ),
    ]
