# Generated by Django 4.2.4 on 2023-11-26 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-avatar.png', help_text='Maximum file size: 5 MB. Allowed extensions: .png or .jpeg', upload_to='Profile_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png, jpeg'])]),
        ),
    ]
