# Generated by Django 4.2.4 on 2023-11-26 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_create_date_profile_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Profile_images/default/default-avatar.png', help_text='Maximum file size: 5 MB. Allowed extensions: .png or .jpeg', upload_to='Profile_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg'])]),
        ),
    ]
