# Generated by Django 4.2.4 on 2023-11-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_images/default/default-avatar.png', help_text='Maximum file size: 5 MB. Allowed extensions: .png or .jpeg', upload_to='profile_images'),
        ),
    ]
