# Generated by Django 4.2.4 on 2023-11-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialinventory',
            name='price_per_unit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
