# Generated by Django 4.2.4 on 2023-11-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_rawmaterialinventory_price_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialidentifier',
            name='parent_item_code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
