# Generated by Django 4.2.4 on 2023-11-29 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_alter_uom_name'),
        ('production', '0003_alter_rawmaterialidentifier_parent_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomcomponent',
            name='uom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='misc.uom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='quantity_used',
            field=models.FloatField(),
        ),
    ]
