# Generated by Django 4.2.4 on 2023-11-29 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_uom_unit_uom_weightage'),
        ('production', '0004_bomcomponent_uom_alter_bomcomponent_quantity_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomcomponent',
            name='uom',
        ),
        migrations.AddField(
            model_name='rawmaterialcomponent',
            name='uom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='misc.uom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterialinventory',
            name='uom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='misc.uom'),
            preserve_default=False,
        ),
    ]
