# Generated by Django 4.2.4 on 2023-12-05 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0006_remove_rawmaterialcomponent_uom_bomcomponent_uom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterialinventory',
            old_name='log_date',
            new_name='create_date',
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionlog',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterialcomponent',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterialidentifier',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterialinventory',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterialinventory',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
